/* isr.c
 * This file is modified form Bram's Kernel Development Tutorial
 * set up the Interrupt Service Routines,
 * which handle excepitons generated by processor 
 */
// std
#include "../include/defines.h"
// x86
#include "pm.h"
#include "isr.h"

extern "C" void default_isr();

void isr_init(){
    //fault_init();
    /* treat unkown interrupt as fault */
//    int i;
//    for (i = 0; i < NIDT; i++){
//        idt_install(i,(uint32_t)default_isr, SEL_KCODE << 3, GATE_INT, IDT_PR|IDT_DPL_KERN);
//    }
    irq_init();
    fault_init();
}

